# Site settings
title: Please don't stalk me
description: "Welcome to my personal corner of the internet!"
author: Ming Yan

# Build settings
theme: minima # We use a base theme but override the layouts
